### ISSUE TITLE
It works in Sublime Text 3 

### ISSUE THREAD

**Issue by collegeimprovements** [JoshCheek/sublime-text-2-and-3-seeing-is-believing#13]
Seeing is Believing is the most useful plugin I have ever had in Ruby Development. It works charmingly in ST3 also. Thanks :)

**Comment by JoshCheek** [comment]
Yeah, got an awesome PR from @jamox which added the support in, https://github.com/JoshCheek/sublime-text-2-seeing-is-believing/pull/10

Just need to rename it. It's actually easy now, back then, I think it was a lot less clear what that meant (or maybe I was just a lot more ignorant!

Anyway, I'll do that now.

Hoping in about 2 to 3 months to get the time to go through all the editor integrations and polish them up and bring in Traveling Ruby so that the install process is "click a button". With SiB v3, there's some really cool possibilities for editor integration (eg realtime updates).

**Comment by JoshCheek** [comment]
Done.
